### ISSUE TITLE
Not using my releaseRules options

### ISSUE THREAD

**Issue by jbonnier** [huggingface/semver-release-action#4]
I'm trying to use your action but it seem to ignore the `releaseRules`  I pass to `commitAnalyzerPluginOpts`.

Here's how I use it.

```yaml
      - name: Release
        id: release
        uses: huggingface/semver-release-action@latest
        with:
          commitAnalyzerPluginOpts: |
            {
              "preset": "angular",
              "releaseRules": [
                { "type": "docs", "scope": "README", "release": "patch" },
                { "type": "chore", "scope": "tool-versions", "release": "patch" },
                { "type": "refactor", "scope": "core-*", "release": "minor" },
                { "type": "refactor", "release": "patch" },
                { "scope": "no-release", "release": false }
              ]
            }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Here is the logs:

```
[3:45:39 AM] [semantic-release] › ℹ  Running semantic-release version 23.0.8
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[3:45:39 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[3:45:40 AM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/jbonnier/docker-terragrunt
[3:45:40 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[3:45:40 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[3:45:40 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com/)
[3:45:40 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[3:45:40 AM] [semantic-release] › ℹ  Found git tag 1.0.0 associated with version 1.0.0 on branch main
[3:45:40 AM] [semantic-release] › ℹ  Found 4 commits since last release
[3:45:40 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(tool-versions): Update Dockerfile with new Terraform and Terragrunt versions [skip ci]
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: Rely entirely on  for release configuration
[3:45:[40](https://github.com/jbonnier/docker-terragrunt/actions/runs/11155509482/job/31006560562#step:9:41) AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: Add plugins configuration to the  file
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(tool-versions): Update Dockerfile with new Terraform and Terragrunt versions [skip ci]
[3:45:40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:[45](https://github.com/jbonnier/docker-terragrunt/actions/runs/11155509482/job/31006560562#step:9:46):40 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 4 commits complete: no release
[3:45:40 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:45:40 AM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
No release published.
```

According to my config, this commit `chore(tool-versions): Update Dockerfile with new Terraform and Terragrunt versions [skip ci]` should trigger a patch but it doesn't.
